apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result
spec:
  type: LoadBalancer
  ports:
    - name: 'result-service'
      port: 5001
      targetPort: 80
      nodePort: 31005