apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: vote
spec:
  type: LoadBalancer
  ports:
    - name: 'vote-service'
      port: 5000
      targetPort: 80
      nodePort: 31000