apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: worker
    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1
          
  
  